ALTO_VENTANA = 450
ANCHO_VENTANA = 800
TIEMPO_CADA_JUEGO = 60
TIEMPO_ANUNCIO = 5
VELOCIDAD_JUGADOR = 4 #Minima puede ser 2
DIFICULTAD = [VELOCIDAD_JUGADOR-1,VELOCIDAD_JUGADOR,VELOCIDAD_JUGADOR+1]
MAX_JUGADORES_TEAM=1